name: Publicar Docker no Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir a imagem Docker
        run: docker build -t odevthomas/desafio-docker-node .

      - name: Publicar a imagem no Docker Hub
        run: docker push odevthomas/desafio-docker-node
